// =============================================================================
// Запрос: _BASE_KG_INN
// Excel 2016 (русский), Power Query (M)
// =============================================================================
//
// Назначение:
//   Из смарт-таблицы _base_kg разобрать колонку «Компании группы (ЕРЗ)»
//   с фрагментами вида «Название (ИНН 1234567890)», связать с колонкой
//   «Наименование, регион» и собрать таблицу уникальных ИНН.
//
// Агрегация:
//   — разные наименования у одного ИНН → через «;» + перенос строки;
//   — разные «Наименование, регион» у одного ИНН → через «;» + перенос строки;
//   — «Кол-во регионов» — число уникальных «Наименование, регион»;
//   — «Наименование без города» — уникальные части до первой запятой;
//   — «Кол-во наименований без города» — число таких урезанных названий.
//
// Параметры в начале запроса согласованы с блоком base_kg_inn_extract в config.json.
// Форматирование листа (ширины, freeze=1 колонка, жирные заголовки) задаётся после
// загрузки в Excel либо выполняется Python-скриптом src/extract_base_kg_inn.py.
//
// Подключение:
//   1) Данные → Создать запрос → Из другого источника → Пустой запрос
//   2) Расширенный редактор → вставить этот код
//   3) Готово → загрузить на новый лист, переименовать запрос в _BASE_KG_INN
// =============================================================================

let
    // ─── Параметры (как в config.json → base_kg_inn_extract) ───────────────
    Имя_таблицы = "_base_kg",
    Имя_колонки_регион = "Наименование, регион",
    Имя_колонки_компании = "Компании группы (ЕРЗ)",
    Ключевое_слово_инн = "ИНН",
    // Разделители компаний: все заменяются на канонический «;» перед Split.
    Разделители_компаний = {";", ","},
    Канонический_разделитель = ";",
    Соединитель_значений = ";#(lf)",

    Имя_выхода_инн = "ИНН",
    Имя_выхода_наименование = "Наименование",
    Имя_выхода_регион = "Наименование, регион",
    Имя_выхода_кол_регионов = "Кол-во регионов",
    Имя_выхода_имя_без_города = "Наименование без города",
    Имя_выхода_кол_без_города = "Кол-во наименований без города",

    // Порядок колонок результата (как в Python / config).
    Колонки_результата = {
        Имя_выхода_инн,
        Имя_выхода_наименование,
        Имя_выхода_регион,
        Имя_выхода_кол_регионов,
        Имя_выхода_имя_без_города,
        Имя_выхода_кол_без_города
    },

    // ─── Источник ──────────────────────────────────────────────────────────
    Источник_base_kg =
        Excel.CurrentWorkbook(){[Name = Имя_таблицы]}[Content],

    // Оставляем только нужные колонки (если есть).
    Колонки_есть =
        List.Intersect(
            {Имя_колонки_регион, Имя_колонки_компании},
            Table.ColumnNames(Источник_base_kg)
        ),

    Выбранные_колонки =
        Table.SelectColumns(Источник_base_kg, Колонки_есть),

    // ─── Функции ───────────────────────────────────────────────────────────
    fnВТекст = (значение as any) as text =>
        Text.Trim(if значение = null then "" else Text.From(значение)),

    fnПоле = (строка as record, имя as text) as any =>
        try Record.Field(строка, имя) otherwise null,

    // Нормализация разделителей: каждый из Разделители_компаний → «;».
    fnНормализоватьРазделители = (текст as text) as text =>
        List.Accumulate(
            Разделители_компаний,
            текст,
            (state, sep) =>
                if sep = null or sep = "" or sep = Канонический_разделитель then
                    state
                else
                    Text.Replace(state, sep, Канонический_разделитель)
        ),

    // Только цифры из текста (без Text.ToList / Text.Select — Excel 2016).
    fnТолькоЦифры = (текст as text) as text =>
        let
            символы = List.Buffer(Text.ToList(текст)),
            цифры = List.Select(символы, each _ >= "0" and _ <= "9")
        in
            Text.Combine(цифры),

    // Разбор одного фрагмента «Название (ИНН 123…)» → [Name=, Inn=] или null.
    fnРазобратьФрагмент = (фрагмент as text) as nullable record =>
        let
            t = Text.Trim(фрагмент),
            маркер = "(" & Ключевое_слово_инн & " ",
            lowerT = Text.Lower(t),
            lowerМаркер = Text.Lower(маркер),
            поз = Text.PositionOf(lowerT, lowerМаркер),
            результат =
                if t = "" or поз < 0 then
                    null
                else
                    let
                        имя = Text.Trim(Text.Start(t, поз)),
                        послеМаркера = Text.Middle(t, поз + Text.Length(маркер)),
                        доСкобки = Text.Trim(Text.BeforeDelimiter(послеМаркера, ")")),
                        инн = fnТолькоЦифры(доСкобки),
                        ok = имя <> "" and инн <> ""
                    in
                        if ok then [Name = имя, Inn = инн] else null
        in
            результат,

    // Строка источника → список записей {Name, Inn, Region}.
    fnПарыИзСтроки = (строка as record) as list =>
        let
            регион = fnВТекст(fnПоле(строка, Имя_колонки_регион)),
            сырой = fnВТекст(fnПоле(строка, Имя_колонки_компании)),
            норм = fnНормализоватьРазделители(сырой),
            части =
                if норм = "" then
                    {}
                else
                    List.Transform(Text.Split(норм, Канонический_разделитель), each Text.Trim(_)),
            разобранные =
                List.Transform(
                    части,
                    (p) =>
                        let
                            rec = fnРазобратьФрагмент(p)
                        in
                            if rec = null then
                                null
                            else
                                [Name = rec[Name], Inn = rec[Inn], Region = регион]
                ),
            безПустых = List.Select(разобранные, each _ <> null)
        in
            безПустых,

    // Часть «Наименование, регион» до первой запятой.
    fnИмяДоЗапятой = (регион as text) as text =>
        Text.Trim(Text.BeforeDelimiter(регион, ",")),

    // Уникальные непустые регионы из подтаблицы группы.
    fnУникРегионы = (т as table) as list =>
        List.Distinct(
            List.Select(
                Table.Column(т, Имя_выхода_регион),
                each _ <> null and Text.Trim(Text.From(_)) <> ""
            )
        ),

    // Уникальные наименования без города из списка регионов.
    fnУникИменаБезГорода = (регионы as list) as list =>
        List.Distinct(
            List.Select(
                List.Transform(регионы, each fnИмяДоЗапятой(Text.From(_))),
                each _ <> ""
            )
        ),

    // ─── Развёртка всех пар ────────────────────────────────────────────────
    СписокПар =
        List.Combine(
            List.Transform(Table.ToRecords(Выбранные_колонки), each fnПарыИзСтроки(_))
        ),

    ТаблицаПар =
        if List.IsEmpty(СписокПар) then
            #table(
                {Имя_выхода_инн, Имя_выхода_наименование, Имя_выхода_регион},
                {}
            )
        else
            Table.FromRecords(
                List.Transform(
                    СписокПар,
                    each Record.FromList(
                        {[Inn], [Name], [Region]},
                        {Имя_выхода_инн, Имя_выхода_наименование, Имя_выхода_регион}
                    )
                )
            ),

    // ─── Агрегация по уникальному ИНН ──────────────────────────────────────
    // Сохраняем порядок первого появления ИНН (GroupKind.Local).
    Сгруппированная =
        Table.Group(
            ТаблицаПар,
            {Имя_выхода_инн},
            {
                {
                    Имя_выхода_наименование,
                    each
                        Text.Combine(
                            List.Distinct(
                                List.Select(
                                    Table.Column(_, Имя_выхода_наименование),
                                    each _ <> null and Text.Trim(_) <> ""
                                )
                            ),
                            Соединитель_значений
                        ),
                    type text
                },
                {
                    Имя_выхода_регион,
                    each Text.Combine(fnУникРегионы(_), Соединитель_значений),
                    type text
                },
                {
                    Имя_выхода_кол_регионов,
                    each List.Count(fnУникРегионы(_)),
                    type number
                },
                {
                    Имя_выхода_имя_без_города,
                    each
                        Text.Combine(
                            fnУникИменаБезГорода(fnУникРегионы(_)),
                            Соединитель_значений
                        ),
                    type text
                },
                {
                    Имя_выхода_кол_без_города,
                    each List.Count(fnУникИменаБезГорода(fnУникРегионы(_))),
                    type number
                }
            },
            GroupKind.Local
        ),

    Результат =
        Table.ReorderColumns(Сгруппированная, Колонки_результата)
in
    Результат
